# Generated by Django 4.2.2 on 2025-12-24 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subredditpost',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Worker assigned to this post', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='body',
            field=models.TextField(blank=True, help_text='Post body/selftext'),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='fetched_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When we fetched this post'),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='num_comments',
            field=models.IntegerField(default=0, help_text='Number of comments'),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='permalink',
            field=models.CharField(blank=True, db_index=True, help_text='Reddit permalink', max_length=500),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='post_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reddit post ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='score',
            field=models.IntegerField(default=0, help_text='Reddit score'),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('replied', 'Replied')], db_index=True, default='pending', help_text='Post processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='upvotes',
            field=models.IntegerField(default=0, help_text='Number of upvotes'),
        ),
        migrations.AlterField(
            model_name='subredditpost',
            name='author',
            field=models.CharField(default='[deleted]', max_length=100),
        ),
        migrations.AlterField(
            model_name='subredditpost',
            name='created_utc',
            field=models.DateTimeField(help_text='Post creation time (UTC)'),
        ),
        migrations.AlterField(
            model_name='subredditpost',
            name='subreddit',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subredditpost',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subredditpost',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='subredditpost',
            index=models.Index(fields=['status', '-fetched_at'], name='crawler_sub_status_b1eb52_idx'),
        ),
        migrations.AddIndex(
            model_name='subredditpost',
            index=models.Index(fields=['subreddit', '-fetched_at'], name='crawler_sub_subredd_d084d1_idx'),
        ),
    ]
