"""Add keywords and post status log tables

Revision ID: 48aab251e87b
Revises: 
Create Date: 2025-12-25 12:53:58.562141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aab251e87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False, comment='Keyword text (normalized to lowercase)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Keyword type: primary (intent) or secondary (domain/topic)'),
    sa.Column('client_id', sa.String(length=100), nullable=True, comment='Client identifier for multi-tenant support'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this keyword is enabled for matching'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When this keyword was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When this keyword was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_client_enabled', 'keywords', ['client_id', 'enabled'], unique=False)
    op.create_index('idx_keyword_type_enabled', 'keywords', ['type', 'enabled'], unique=False)
    op.create_index('idx_keyword_word_type', 'keywords', ['word', 'type'], unique=False)
    op.create_index(op.f('ix_keywords_client_id'), 'keywords', ['client_id'], unique=False)
    op.create_index(op.f('ix_keywords_enabled'), 'keywords', ['enabled'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_type'), 'keywords', ['type'], unique=False)
    op.create_index(op.f('ix_keywords_word'), 'keywords', ['word'], unique=False)
    op.create_table('post_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='Reference to posts.id'),
    sa.Column('reddit_post_id', sa.String(length=50), nullable=True, comment='Reddit post ID for easy lookup'),
    sa.Column('old_status', sa.String(length=20), nullable=True, comment='Previous status'),
    sa.Column('new_status', sa.String(length=20), nullable=False, comment='New status'),
    sa.Column('changed_by', sa.String(length=100), nullable=True, comment='User/system that made the change'),
    sa.Column('change_reason', sa.String(length=200), nullable=True, comment="Reason for status change (e.g., 'auto_expire', 'manual_assign')"),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the status change occurred'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_log_post', 'post_status_logs', ['post_id', 'changed_at'], unique=False)
    op.create_index('idx_status_log_reddit_post', 'post_status_logs', ['reddit_post_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_post_status_logs_changed_at'), 'post_status_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_post_status_logs_id'), 'post_status_logs', ['id'], unique=False)
    op.create_index(op.f('ix_post_status_logs_post_id'), 'post_status_logs', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_status_logs_reddit_post_id'), 'post_status_logs', ['reddit_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_status_logs_reddit_post_id'), table_name='post_status_logs')
    op.drop_index(op.f('ix_post_status_logs_post_id'), table_name='post_status_logs')
    op.drop_index(op.f('ix_post_status_logs_id'), table_name='post_status_logs')
    op.drop_index(op.f('ix_post_status_logs_changed_at'), table_name='post_status_logs')
    op.drop_index('idx_status_log_reddit_post', table_name='post_status_logs')
    op.drop_index('idx_status_log_post', table_name='post_status_logs')
    op.drop_table('post_status_logs')
    op.drop_index(op.f('ix_keywords_word'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_type'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_enabled'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_client_id'), table_name='keywords')
    op.drop_index('idx_keyword_word_type', table_name='keywords')
    op.drop_index('idx_keyword_type_enabled', table_name='keywords')
    op.drop_index('idx_keyword_client_enabled', table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###





