# Generated by Django 4.2.2 on 2023-07-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_soup', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subreddits',
            unique_together={('title',)},
        ),
    ]
